
import React from 'react';
import { 
  Play, 
  Square, 
  Upload, 
  Database, 
  Mail, 
  Code, 
  FileJson, 
  GitBranch, 
  CheckCircle2,
  Clock,
  FileSpreadsheet,
  Terminal,
  Search,
  Sparkles,
  Phone,
  Plug,
  MessageCircle,
  Download,
  Cookie,
  Save,
  FileText,
  Globe,
  Brain,
  Layers,
  LayoutTemplate,
  Target,
  LogIn,
  Workflow as WorkflowIcon
} from 'lucide-react';

import { NodeType, EventType } from './types';

export const COMPONENT_METADATA: Record<NodeType, { label: string; icon: React.ReactNode; color: string }> = {
  'start': { label: 'Start', icon: <Play size={18} />, color: 'text-emerald-500' },
  'stop': { label: 'Stop', icon: <Square size={18} />, color: 'text-rose-500' },
  'file-upload': { label: 'File Upload', icon: <Upload size={18} />, color: 'text-blue-500' },
  'remove-duplicate': { label: 'Remove Duplicate', icon: <Layers size={18} />, color: 'text-indigo-500' },
  'json-mapper': { label: 'JSON Mapper', icon: <FileJson size={18} />, color: 'text-cyan-500' },
  'js-expression': { label: 'JS Expression', icon: <Code size={18} />, color: 'text-yellow-600' },
  'delay': { label: 'Delay', icon: <Clock size={18} />, color: 'text-slate-500' },
  'sql': { label: 'SQL', icon: <Database size={18} />, color: 'text-indigo-600' },
  'excel-upload': { label: 'Excel Upload', icon: <FileSpreadsheet size={18} />, color: 'text-emerald-600' },
  'procedure': { label: 'Procedure', icon: <Terminal size={18} />, color: 'text-purple-500' },
  'step-validator': { label: 'Step Validator', icon: <CheckCircle2 size={18} />, color: 'text-orange-500' },
  'conditional': { label: 'Conditional', icon: <GitBranch size={18} />, color: 'text-pink-500' },
  'sql-query': { label: 'SQL Query', icon: <Search size={18} />, color: 'text-blue-600' },
  'dynamic-sql-query': { label: 'Dynamic SQL', icon: <Sparkles size={18} />, color: 'text-violet-500' },
  'email': { label: 'Send Email', icon: <Mail size={18} />, color: 'text-amber-500' },
  'phone-call': { label: 'Phone Call', icon: <Phone size={18} />, color: 'text-green-500' },
  'socket': { label: 'Socket', icon: <Plug size={18} />, color: 'text-gray-600' },
  'text-message': { label: 'Text Message', icon: <MessageCircle size={18} />, color: 'text-indigo-400' },
  'download-file': { label: 'Download File', icon: <Download size={18} />, color: 'text-teal-500' },
  'set-cookie': { label: 'Set Cookie', icon: <Cookie size={18} />, color: 'text-amber-700' },
  'save-file': { label: 'Save File', icon: <Save size={18} />, color: 'text-blue-700' },
  'html-to-pdf': { label: 'HTML to PDF', icon: <FileText size={18} />, color: 'text-rose-600' },
  'api-call': { label: 'API Call', icon: <Globe size={18} />, color: 'text-sky-500' },
  'prediction-api-call': { label: 'Prediction API', icon: <Brain size={18} />, color: 'text-fuchsia-500' },
  'ai-vector': { label: 'AI Vector', icon: <Database size={18} />, color: 'text-violet-600' },
  'ai-template': { label: 'AI Template', icon: <LayoutTemplate size={18} />, color: 'text-purple-600' },
  'google-ads': { label: 'Google Ads', icon: <Target size={18} />, color: 'text-red-500' },
  'login': { label: 'Login', icon: <LogIn size={18} />, color: 'text-emerald-600' },
  'workflow-caller': { label: 'Workflow Caller', icon: <WorkflowIcon size={18} />, color: 'text-blue-600' },
};

export const EVENT_TYPES: { value: EventType; label: string }[] = [
  { value: 'call', label: 'API Call' },
  { value: 'audit', label: 'Audit Log' },
  { value: 'goto', label: 'Go to Page' },
  { value: 'save', label: 'Save Variable' },
  { value: 'open', label: 'Open Component' },
  { value: 'close', label: 'Close Component' },
  { value: 'gotoUrl', label: 'Open URL' },
  { value: 'setSessionStorage', label: 'Set Session Storage' },
  { value: 'removeSessionStorage', label: 'Remove Session Storage' },
  { value: 'copyToClipboard', label: 'Copy to Clipboard' },
  { value: 'socketLogout', label: 'Logout' },
  { value: 'removeUrlParams', label: 'Remove URL Params' },
];
